project:
  type: website
  render:
    - "*.qmd"
    - "!img/"
  output-dir: docs
  resources:
    - "files/"


website:
  title: "KIAH"
  site-url:  https://kiah1013.github.io
  navbar:
    right:
      - index.qmd
      - resume.qmd
      - about.qmd
      - text: Home
        href: https://home.kiah1013.github.io
      - text: Resume
        href: https://resume.kiah1013.github.io
      - text: About Me
        href: https://about.kiah1013.github.iokiah1013.github.io

