---
title: "Resume"
---

# Kiah Epperson
255 Fulton St. • Camarillo, CA 93010
Phone: (805) 340-7610 • E-mail: epperson.kiah@yahoo.com

---

## Objective
Eager to leverage dual BS degrees in Computer Science and Mathematics to innovate and solve complex problems in a dynamic tech environment.

---

## Education
**California State University Channel Islands** | Camarillo, CA
Bachelor of Science in Computer Science
Bachelor of Science in Mathematics with emphasis in Applied Mathematics
- Will graduate in December 2024
- Involved in a semester-long project to create a coloring book application for iOS devices

**2021–2024**

---

## Work Experience

**Amazon Fulfillment Center** | Camarillo, CA
Amazon Shipping Warehouse Worker
**November 2023 – January 2024**
- Managed the accurate and timely picking, packing, and shipping of over 500 daily orders, maintaining a 99% accuracy rate and contributing to the center's efficiency and customer satisfaction.
- Operated warehouse machinery, including forklifts and pallet jacks, adhering to strict safety guidelines to ensure a safe working environment for all employees.
- Utilized Amazon’s warehouse management systems for inventory control, order tracking, and shipping logistics, enhancing operational efficiency and reducing error rates.

**Rite-Aid** | Ojai, CA
Shift Supervisor
**November 2021 – October 2022**
- Led a team of 10+ employees, overseeing shift operations to ensure excellent customer service, operational efficiency, and adherence to company policies.
- Managed inventory levels, performed regular stock assessments, and coordinated the ordering of new supplies, reducing inventory discrepancies by 20%.
- Handled cash management responsibilities, including till balancing, deposits, and transaction verifications, maintaining impeccable financial accuracy.
- Resolved customer complaints and issues promptly, employing strong problem-solving skills to maintain high levels of customer loyalty and repeat business.

---

## Languages
- Basic Knowledge of Spanish
- Fluent in English
